const products = [
    {
      id: "1",
      tipo: "moveis",
      image: "src/imgs/moveis.png",
      name: "Mobilia",
      description: "Mobilia pá tu",
    },
    {
      id: "2",
      tipo: "moveis",
      image: "src/imgs/gabinete.png",
      name: "Criado Mudo",
      description: "Um Criado",
    },
    {
      id: "3",
      tipo: "alimentos",
      image: "src/imgs/alimentos.png",
      name: "Lanche-SUS",
      description: "Da concorrencia",
    },
    {
      id: "4",
      tipo: "eletronicos",
      image: "src/imgs/compilterNe.png",
      name: "Monitor",
      description: "Só nos compilter",
    },
    {
      id: "5",
      tipo: "cozinha",
      image: "src/imgs/cozinha.png",
      name: "Cozinha",
      description: "E a janta?",
    },
    {
      id: "6",
      tipo: "alimentos",
      image: "src/imgs/dieta.png",
      name: "Saladinha",
      description: "Projetinho verão",
    },
    {
      id: "7",
      tipo: "eletronicos",
      image: "src/imgs/eletronicos.png",
      name: "Rolex",
      description: "Tem hora?",
    },
    {
      id: "8",
      tipo: "eletronicos",
      image: "src/imgs/furar.png",
      name: "Furadeira",
      description: "E a makita nd?",
    },
    {
      id: "9",
      tipo: "eletronicos",  
      image: "src/imgs/mouseDesk.png",
      name: "Mouse",
      description: "Sense pura",
    },
    {
      id: "10",
      tipo: "moveis",
      image: "src/imgs/mobilia-domestica.png",
      name: "Mobilia",
      description: "Senta ae",
    },
    {
      id: "11",
      tipo: "alimentos",
      image: "src/imgs/nutricao.png",
      name: "Pizza",
      description: "Quatro queijos",
    },
    {
      id: "12",
      tipo: "eletronicos",
      image: "src/imgs/porta-digital.png",
      name: "Fechadura",
      description: "Abre ae",
    },
    {
      id: "13",
      tipo: "eletronicos",
      image: "src/imgs/keyboard.png",
      name: "Teclado",
      description: "0 bala",
    },
  ];

  export default products;